cargo-features = ["edition"]

[package]
name = "slog"
version = "2.2.3"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Structured, extensible, composable logging for Rust"
keywords = ["log", "logging", "structured", "hierarchical"]
categories = ["development-tools::debugging"]
license = "MPL-2.0/MIT/Apache-2.0"
documentation = "https://docs.rs/slog"
homepage = "https://github.com/slog-rs/slog"
repository = "https://github.com/slog-rs/slog"
readme = "README.md"
edition = "2018"

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[profile.bench]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[features]
nested-values = ["erased-serde"]
dynamic-keys = []
std = []
default = ["std"]

max_level_off   = []
max_level_error = []
max_level_warn  = []
max_level_info  = []
max_level_debug = []
max_level_trace = []

release_max_level_off   = []
release_max_level_error = []
release_max_level_warn  = []
release_max_level_info  = []
release_max_level_debug = []
release_max_level_trace = []

[dependencies]
erased-serde = { version = "0.3", optional = true }

[dev-dependencies]
slog-term = "2"
slog-async = "2"

[package.metadata.docs.rs]
features = ["std", "nested-values", "dynamic-keys"]

[patch.crates-io]
slog-term = { git = "https://github.com/jechase/slog-term", branch = "2018_edition" }
slog-async = { git = "https://github.com/jechase/slog-async", branch = "2018_edition" }
